### ISSUE TITLE
Error when attempting to use the Add Experience Points/End of session Macro

### ISSUE THREAD

**Issue by LEGION001** [Jagusti/fvtt-wfrp4e-gmtoolkit#114]
So I've been having this issue where when attempting to use the add experience points macro it throws me this error. 

![89098533bbd3c75e5e694e82ae4b0407](https://user-images.githubusercontent.com/38386203/175775705-9c7790c5-dd37-4c02-a3ee-78219a73f6d0.jpg)

I've had the chance to do some troubleshooting today and this error happens even when only running the core WFRP module and WFRP GM toolkit. But more importantly it seems to happen only with certain characters. I.e I targeted certain characters and the macro only works with one of them. The moment I try and give any other character XP via the macro it doesn't work. 

I then proceeded to try and rebuild each character manually, and while that ended up making the macro work for one character that had previously been throwing that error, when I rebuilt another character it once again threw the error.

If there is any additional info you need, let me know.

**Comment by Jagusti** [comment]
Thanks for the bug report. Can you check and confirm the following please: 
- WFRP4e system version (latest is 5.3.0)
- GM Toolkit module version (latest is 0.9.3)
- Add XP macro version (you can find this at the bottom of the macro script, latest is 0.9.3, 2022-01-24)

If you have the latest of all, can you 
- export the characters (right click from the actor directory) 
- post the files here or send me to then via DM on Discord
- let me know for each actor whether it does or does not work

I may need to log into your server of I can't replicate it.  Let me know your Discord handle, and I'll reach out to you there to arrange if needed. It's useful in case there's something else to check as well. 

Cheers!

**Comment by LEGION001** [comment]
Currently on 5.3.0 of WFRP4e, 0.9.3 GM Toolkit and the macro is 0.9.3.

I've uploaded the actors together into a ZIP attached here. 

The only one that works is Urathus, all the others don't. 

That said, I don't quite know what I did, but apparently something I did caused something to change as now the targeting of each individual actor does work, but the automatic version of the module, i.e when nothing is targeted and its supposed to default to the actors owned by PC's still runs into the same problem. If I change the permissions on each character so only Urathus is owned by his player then it works, but if I try the same with any of the others it doesn't. 


And here is my discord: LEGION#5187


[Actors.zip](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/8984929/Actors.zip)

**Comment by Jagusti** [comment]
Looks like this is happening on new actors that have no current XP. The `current` value is calculated, rather than in the template, so isn't present by default. However, it is referenced in the macro when not targeting actors via their token. 
Note to self: that reference looks like it's redundant now, so can be removed as part of the fix.
