### ISSUE TITLE
Incompatibility with Babele

### ISSUE THREAD

**Issue by Txus5012** [Jagusti/fvtt-wfrp4e-gmtoolkit#135]
It seems that the new version brings an incompatibility with Babele module.

The Item compendiums show the untranslated version when opening them (and also when dragging them to a sheet, etc.).
![Coat](https://user-images.githubusercontent.com/87753744/180468167-6ea13938-f533-4a2e-88cb-63455e508ed3.jpg)

Other compendiums (Actors, Journals, etc.) aren't affected.

I think it's caused by this "compileItems" function in utility.mjs. (Just because I removed it and the translation showed again).
![Utility](https://user-images.githubusercontent.com/87753744/180468530-327bdb6b-902b-4ec2-ba5f-4505e669cd70.jpg)

I'm working in the Spanish translation, but I tried the French and Japanese ones and have the same issue.

**Comment by Yasnen** [comment]
In my environment, compendiums localization by Babel is working fine. However, the drop-down list of skills in the quick test is not localized.
Localization of Compendium data is performed when it is displayed in the game.
So it is better to get the data from the item directory or from the skills owned by the target actors.

**Comment by Jagusti** [comment]
This is tricky. I was certainly frustrated when I added this that I couldn't translate items from a compendium.

I feel like it's a lot messier to traverse all world actors (which would include NPC characters and creatures), compile and de-dupe their skills rather than getting a master list from compendia. 

The trade-off is certainly localisation. I need to think about this a bit more and decide how I want to proceed. 

Thanks for flagging it. The feedback is very welcome.

**Comment by Txus5012** [comment]
This is more a workaround than a solution, but making the game.packs.filter look for skills at least make the issue affect only the Skills compendium.

Following this line of thinking, I made a copy of the compendium and made gmtoolkit search inside that new compendium.
![Utility2](https://user-images.githubusercontent.com/87753744/180503534-ff37d161-c7ea-4aea-8ad0-aefac3da1967.jpg)
The skill dropdown list will still be in English (we can type the name of the skill, so it will still be usable), but at least it doesn't mess with the translation of compendiums.

**Comment by Txus5012** [comment]
I'll write this in case it's useful. I've noticed that opening the WFRP Browser fixes all the compendium translations. Must be done everytime the world is launched, though.
But after translating, the group tests doesn't work when selecting a skill from a list. It does work when manually typing the translated skill.

**Comment by Jagusti** [comment]
I'm curious that you both have slightly different experiences with Babele. Could you share what settings/options you are using, and the repo that you are using for translation source please?  I haven't used it before this issue, and not sure I have it set up as expected. Thanks
