### ISSUE TITLE
Reset fortune macro fails with errors in console.

### ISSUE THREAD

**Issue by bluetardis** [Jagusti/fvtt-wfrp4e-gmtoolkit#149]
When running reset fortune the following errors in the console are shown.  Macro fails with no feedback to GM.

![Screen Shot 2022-07-30 at 10 58 44 am](https://user-images.githubusercontent.com/5024761/181864702-5bd6850a-8b87-41d7-84b2-eededef7fcbe.png)

**Comment by bluetardis** [comment]
Clicking on the VM1170:14 link takes me to the AddXP macro

**Comment by bluetardis** [comment]
0.9.3 works as expected.

**Comment by Jagusti** [comment]
This error occurs for me when running the macro on actors that aren't type 'character', so NPC and Creature actors, who do not have Fortune. Is this the scenario here?

**Comment by bluetardis** [comment]
This is on a regular player character, associated with a user.  Let me know if you want access or want me to check anything else.
Also tried with getting the user to login - same error.

**Comment by bluetardis** [comment]
Doing more investigation.

Following on from your tip in XP I made the following change.
```//	let party = game.gmtoolkit.utility.getGroup("party")```
```let party = game.gmtoolkit.utility.getGroup("company") ```

This initially failed.

However on a hunch I deleted all Death on the Reik content as when updating this I had seen an error in the console -  I posted in moo's discord earlier.  Deleting it removes the error from the console.

And if I use company then it works.....if I use party then I still get the error.  Doesnt matter what I target.

**Comment by bluetardis** [comment]
After deleting and reinstalling Death on the Reik.
Fortune macro still works with the change from `party` to `company`.

**Comment by Jagusti** [comment]
So, trying to understand this a bit better ...
- company works but party still doesn't?
- do any of the actors get their Fortune reset?
Can you share an export of the affected actors please?

**Comment by bluetardis** [comment]
Confirming that` "company"` works: (all player owned character objects get fortune reset)
technically "eeek" and "NoName" are pets but they use full character sheets as per: 
https://github.com/simulacrum-1/wfrp4e-laws-pet-shoppe
![Screen Shot 2022-07-31 at 8 17 24 am](https://user-images.githubusercontent.com/5024761/182002003-b564f6fd-8995-4a90-8d2f-ffd8deb56e85.png)

Using `"party"` throws the following error:
![Screen Shot 2022-07-31 at 8 18 44 am](https://user-images.githubusercontent.com/5024761/182002024-e81c7e0e-a5c2-44bd-8827-4a8350ee62a3.png)

Including the code as I have an extra line (so I could easily switch between party and company)
![Screen Shot 2022-07-31 at 8 19 28 am](https://user-images.githubusercontent.com/5024761/182002043-d7de743d-a107-469f-a2e3-1a657d8d1d7b.png)

**Comment by bluetardis** [comment]
Here is a sample of a regular character (the one I was selecting/targeting):
[fvtt-Actor-nagy-rattlebum.json.zip](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/9227673/fvtt-Actor-nagy-rattlebum.json.zip)

**Comment by bluetardis** [comment]
Issue with an NPC being assigned a user. (Observer) and this has been removed.  This allowed the "party" to work but it only selected the basic party characters.

Made changes from `party` to `company` as suggested and this is a suitable workaround.  

Enhancement going forward is https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues/151
