### ISSUE TITLE
Player lacks permission to update actor

### ISSUE THREAD

**Issue by gravagehulk** [Jagusti/fvtt-wfrp4e-gmtoolkit#150]
This error occurs regularly throughout the game. I verified that it was GM tools by disabling the module and repeating the steps. It happens any time advantage gets updated on another player's token, such as when they are added to the combat tracker or during combat. Screenshot of console error followed by the settings of the GM Toolkit module.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/69117052/181865318-a5e1976f-8f71-459e-b933-f70dff98dd6d.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/69117052/181865346-95cc8753-3342-421d-b4e3-05cafe7ea0e6.png">

**Comment by gravagehulk** [comment]
Here's another screenshot that seemed to be related to updating wounds:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/69117052/181877646-2f218a62-3440-48a9-ab75-3ded901e5121.png">

**Comment by Jagusti** [comment]
Thanks for this. Remind me, does the GM and/or player get a notification in Foundry as well (not just console)?

**Comment by gravagehulk** [comment]
The GM never sees them. Just the players.

**Comment by Jagusti** [comment]
I've got a fix, I think ... would you be willing to try this out? 

If so, simply extract the contents of the attached zip into your foundry `Data/modules/wfrp4e-gm-toolkit` folder ... best to remove the previous content, or uninstall the module, and extract the zip into a new `wfrp4e-gm-toolkit` folder. 

You can find the location of the Data folder by checking the Configuration tab of the Foundry launch screen - it's the `User Data Path`. 

Hit me up on Discord @Jagusti#3610 if you need help.
[wfrp4e-gm-toolkit.zip](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/9226612/wfrp4e-gm-toolkit.zip)

**Comment by gravagehulk** [comment]
Normally, I'd be happy to, but the problem is that it's not my game. The only reason I noticed this is because I'm a player. And the only way to test it would be for me to install this in a world of my own and have other people connect and see if they see the error.

I can talk to the GM of the game, but he's not very technical. I'll let you know if I can work something out.

**Comment by Jagusti** [comment]
Fair enough, lmk how it goes. If he's on Discord, I'm happy to go through it with him, so feel free to bring him into the conversation over there.

**Comment by gravagehulk** [comment]
Yes sir. Thanks for working on this so quickly. I definitely want to help, just have to work out some logistics.

**Comment by bluetardis** [comment]
@Jagusti I did some basic testing.  Was seeing an error in the player console log on clearing advantage at the end of combat.
I made the changes to the affected files only (looking at datestamp).

Restarted the server (to ensure everything was clear)

This seems to have corrected the errors!

**Comment by Jagusti** [comment]
Thanks @bluetardis  ... @gravagehulk I'll push a release soon when I get a chance, so your GM should be able to just update without technical hoop jumping. If there's still an issue, we can pick it up again.

**Comment by gravagehulk** [comment]
So, we finally had a chance to play again and we're still getting this error. Latest version of WFRP4e and this module. Foundry version 9, build 280:
<img width="552" alt="Screen Shot 2022-09-03 at 20 24 11 PM" src="https://user-images.githubusercontent.com/69117052/188293193-0f84923c-4241-4781-9ae7-c1b20a6b9716.png">
<img width="279" alt="Screen Shot 2022-08-26 at 21 09 32 PM" src="https://user-images.githubusercontent.com/69117052/188293195-a28e8d38-2edd-49ac-b51e-3cc176836d22.png">
