### ISSUE TITLE
Add group selection option for Session Turnover macros

### ISSUE THREAD

**Issue by Jagusti** [Jagusti/fvtt-wfrp4e-gmtoolkit#151]
This enhancement supercedes #117 for Session Turnover macros. 

- [x] Add group type selection option for Session Management (options: party (default), company)
- [x] Apply to Add XP macro
- [x] Apply to Reset Fortune macro

**Comment by bluetardis** [comment]
Stretch goals: 

- [x] Make Secret Group Test (This is more important as pets tend to have high perception or a sense)
- [x] Apply to Dark Whispers (for completeness if possible but this is unlikely to be used)

**Comment by Jagusti** [comment]
> Make Secret Group Test  (This is more important as pets tend to have high perception or a sense)

This is already an option in `Group Test Settings` ... or am I missing something from what you're asking? 

![image](https://user-images.githubusercontent.com/521096/182018049-9ffd6351-967f-4e13-a978-131fc7770486.png)

**Comment by bluetardis** [comment]
_Make Secret Group Test (This is more important as pets tend to have high perception or a sense)_
Not sure why it didn't work earlier but just started world back up and its working fine!
