### ISSUE TITLE
Add FVTT Version 10 Compatibility

### ISSUE THREAD

**Issue by Jagusti** [Jagusti/fvtt-wfrp4e-gmtoolkit#156]
This issue tracks scope and progress of functional compatibility with [**Foundry VTT v10**.277](https://foundryvtt.com/releases/10.277) and [**WFRP4e v6**.0.0.9](https://github.com/moo-man/WFRP4e-FoundryVTT/releases/tag/6.0.0.9).

- The aim is to eliminate breaking errors and minimise warnings to get a working version of the GM Toolkit ready with minimal delay.
- For non-breaking changes, some refactoring may be carried out as part of this migration to leverage new v10 patterns and models. 
- Any significant enhancements (eg, vision modes) or extensive rewriting will be deferred until after compatibility tasks are completed. 

Reference: https://foundryvtt.com/article/migration/

Key for list below:
- [`commit`]() link to related commit / pr
- 9️⃣  no change made for compatibility

### Module

- [x] Manifest (id, relationships, compatibility) [`8d679ca`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/8d679cad0fcc6d847ef76cadbe7934488df9b23d)
- [x] Initialisation 9️⃣ 
- [x] Settings 
  - [x] scripts :nine:
  - [x] templates :nine:
  - [x] debouncedReload [`7c20c11`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/7c20c117d106d7dcc48480f7d9943927c9fd2e7a)
- [x] #161

#### Scripts
- [x] Add Advantage 9️⃣ 
- [x] Clear Advantage 9️⃣ 
- [x] Reduce Advantage 9️⃣ 
- [X] Check Conditions  [c9eb364](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/c9eb364483c5936c677f0dbe0a442ea6dc4046b5)
- [x] Session Turnover :nine:
- [x] Add XP :nine:
- [x] Reset Fortune [`e9b6842`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/e9b684233b3a31361a71897e11115d574d3f86b3)
- [x] Make Secret Group Test
- [x] Send Dark Whispers [`c54bd3a`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/c54bd3af1b7df28e56013bdbeb815b7a2da7137f)
- [x] Toggle Scene Visibility and Light [`383ccc5`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/383ccc5a49fdebc90a626fdaaa528f856348d29e)
- [x] Set Token Vision and Light [`881658`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/881658cb73db7bbe548323a65ac5db7a27f469d4)
- [x] Pull Everyone to Scene [`4334a28`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/4334a283347cfbac672a73ba72e4355e3311c254)
- [x] Simply d100 9️⃣ 
- [x] GM Toolbox [`78f3ff9`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/78f3ff9b546135b80cfa07a575a8c815cf0788c8)
- [x] Toggle Compendium Pack Visibility :nine:

#### Package
- [x] Macro Compendium  [`dddbe4f`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/dddbe4fb24ffc96d5f9e0abb3813620d990587e9)

### RollTable

- [x] Dark Whispers 
- [x] RollTable Compendium  [`dddbe4f`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/dddbe4fb24ffc96d5f9e0abb3813620d990587e9)

### Features

- [x] Toolkit Maintenance (script, template) [`5713431`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/571343143da14de949e2acac7fd26ea6f6f25cf9) [`dddbe4f`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/dddbe4fb24ffc96d5f9e0abb3813620d990587e9)
- [x] Token Hud Extension (module) [`b016b6`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/b016b668061a7d3f4eef7626dc3d457d0030380b)
- [x] Dark Whispers (module, macro, table) [`c54bd3a`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/c54bd3af1b7df28e56013bdbeb815b7a2da7137f)
- [x] Advantage (module, macros) 
  - [x] Assisted Advantage handling [`f4b6738 `](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/f4b6738) 
    - [x] Personal Advantage
    - [x] Context: macro
    - [x] Group Advantage
    - [x] Adding to combat
    - [x] Removing from combat
  - [x] Advanced automation  [`fb83fb7`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/fb83fb7)
    - [x] Context: Outmanoeuvring
    - [x] Context: Winning Opposed Tests
    - [x] Context: Advantage Flags
    - [x] Socket Handling
    - [x] Lose Momentum [`f27889e`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/f27889e)
    - [x] Condition Effects [`0a85244 `](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/0a85244)
- [x] Group Test (module, script, template) [`20febde`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/20febde7a2e5b8e34d2a1821550c96cd96766cad)

### Helpers

- [x] Toolkit
- [x] Utility 
  - [x] hasSkill(), maxStatus(), adjustStatus() [`c9eb364`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/c9eb364483c5936c677f0dbe0a442ea6dc4046b5) [`b016b6`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/b016b668061a7d3f4eef7626dc3d457d0030380b) 
  - [x] getSession(), inCombat() [`56c6cd8`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/56c6cd8995dda7d6d744b966179cb1f12216612a) 
  - [x] getGroup() [`1c15893`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/1c15893da047d0124c85d2bd924450ba346f2244)

### Other
- [x] Spectator Notification [`e1cfddd`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/e1cfddd9b53c31c700b41255df10a91dd649e006)
- [x] Holding Scene Token Movement [`f6da3ac`](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/f6da3aceda719b1b4be8c4cdab3287381cdb553b)
- [x] Stylesheet
  - [x] Token Hud Extension

### Documentation
  - [x] Readme
  - [x] Changelog
  - [ ] Wiki

**Comment by bluetardis** [comment]
Let me know if/when you want help with testing!

**Comment by Jagusti** [comment]
The Dark Whispers table seems to be doing what it needs to in the context of the Send Dark Whispers macro.  There is some strange behaviour when accessing the Rolltable directly, which appears to be a system template issue: https://github.com/moo-man/WFRP4e-FoundryVTT/issues/1200.

**Comment by Jagusti** [comment]
Launching a Skill Test from the Token Hud presents the roll dialog as expected and without user alert. However, there are multiple console warnings raised as part of the test setup for trying to access the Hit Location tables TableResult#data object. This will need to be resolved at a system level. Toolkit behaviour is essentially unaffected, but the console is spammed with compatibility and deprecation warnings. 

```
commons.js:1232 Error: You are accessing the TableResult#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1221:19)
    at TableResult._logV10CompatibilityWarning (commons.js:6058:14)
    at get data [as data] (commons.js:5958:24)
    at wfrp4e.js:131:22
    at EmbeddedCollection.forEach (commons.js:2748:9)
    at WFRP_Tables.getHitLocTable (wfrp4e.js:130:23)
    at ActorWfrp4e.setupSkill (wfrp4e.js:8957:46)
    at HTMLElement.<anonymous> (token-hud-extension.mjs:111:17)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

I've submitted a PR to address some of the issues I've come across: https://github.com/moo-man/WFRP4e-FoundryVTT/pull/1201

**Comment by Jagusti** [comment]
Make Secret Group Test breaks on FVTT 10.277 because of https://github.com/foundryvtt/foundryvtt/issues/7819. Once this is shipped I'll pick this up again.

**Comment by Jagusti** [comment]
Nearly a wrap ... some version admin to do, and maybe publish a release candidate. But this is testable from the v10 branch: https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/tree/v10.
