### ISSUE TITLE
Group advantage - Winning entry - Not applying to defense 

### ISSUE THREAD

**Issue by Ceodryn** [Jagusti/fvtt-wfrp4e-gmtoolkit#159]
As per Up-in-arms new group advantages rules, an advantage is won when winning an opposed test YOU INITIATED during combat. Therefore, no advantages are won on defensive rolls as in the Core RAW.

**Comment by Jagusti** [comment]
Need to add guard here: 
* skip if group advantage AND character != defender 

https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/985e142981b5bc43db09de7efec77b661c80e8c2/modules/advantage.mjs#L406-L407
