### ISSUE TITLE
Customize Skill in Group Tests

### ISSUE THREAD

**Issue by Txus5012** [Jagusti/fvtt-wfrp4e-gmtoolkit#160]
A suggestion for the Group Tests. Not a big deal because there are already 4 presets, but I think this can be nice tweak.

A) When you use the Customize Skill section of the Group Test dialog, "... or specify Skill" is used for the roll even if you select another skill in "Choose Skill ... ". The only way to make the latter be rolled is to manually delete the entry in "... or specify Skill". Maybe it could be better the other way, making the "Choose Skill ..." be the one rolled. Specially because...

B) If you leave blank the "Default Skill", it will type "null" skill in "... or specify Skill". So if you don't want to use this you'll have to manually delete it every time.

![Group Test](https://user-images.githubusercontent.com/87753744/183593164-eabae0cb-9a3b-4b21-80ff-379275a38dd1.jpg)

**Comment by Jagusti** [comment]
Agreed. I'd be looking at a content update in this field if the drop-down changed
- if drop-down skill selected, clear this field
- if drop-down cleared, set to default skill 
- if default skill is null, set to blank (which should show placeholder)

**Comment by Jagusti** [comment]
Noting that I have a potentially relevant pattern in Add XP: https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/dev/scripts/macros/add-xp.js#L22-L35
