### ISSUE TITLE
Reset Fortune not taking into consideration "Luck" Talent

### ISSUE THREAD

**Issue by Yuffyyy** [Jagusti/fvtt-wfrp4e-gmtoolkit#175]
## Checklist
- [X] I can be reached on Discord by my handle: Yuffy#8318

### Versions
 - Foundry VTT:  
 - WFRP4e System: 
 - GM Toolkit:  
 - Macro (if applicable): 

## Steps to reproduce the issue
<!-- Sequence of steps to reproduce the behaviour: eg, 
1. Have a character with "Luck"
2. Spend Fortune points
3. Hit Reste Fortune from the GM Toolkit
4. See that "Luck" is not taken into consideration

**Comment by Jagusti** [comment]
This definitely working for me in this setup using 6.0.0 release of GM Toolkit (see below). Some info about what versions you're using, steps you're taking, exports of character data etc is good.  There's a bunch of checklist tasks in the bug request form which you've not verified, but which will help. 

![image](https://user-images.githubusercontent.com/521096/188719310-909f025a-a794-4a4d-84c6-ff1760d1543a.png)
![image](https://user-images.githubusercontent.com/521096/188719412-483a5e5a-65ee-4e44-a315-31ac05677833.png)
![image](https://user-images.githubusercontent.com/521096/188719451-d73abcb4-6c3c-480d-a540-9896937e8d92.png)

**Comment by Jagusti** [comment]
I tried messaging you on Discord to quickly ascertain some of this, but I can't DM you ... 
![image](https://user-images.githubusercontent.com/521096/188720511-77237ad2-ec7b-4c51-b011-15aeef58003b.png)

**Comment by Yuffyyy** [comment]
Ah ! Yes, opening my Dms now, sorry for that

De : Jag ***@***.***>
Envoyé le :mardi 6 septembre 2022 21:18
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Jagusti/fvtt-wfrp4e-gmtoolkit] Reset Fortune not taking into consideration "Luck" Talent (Issue #175)


I tried messaging you on Discord to quickly ascertain some of this, but I can't DM you ...
[image]<https://user-images.githubusercontent.com/521096/188720511-77237ad2-ec7b-4c51-b011-15aeef58003b.png>

**Comment by Jagusti** [comment]
Resolved via Discord: updated macro version from 0.8.0 to 0.9.5 and deleted multiple macro copies in macro directory.
