### ISSUE TITLE
Several (non-breaking) Errors when updating Group Advantage.

### ISSUE THREAD

**Issue by TheFirst05** [Jagusti/fvtt-wfrp4e-gmtoolkit#184]
### Versions
 - Foundry VTT: v10.285
 - WFRP4e System: 6.1.2
 - GM Toolkit:  6.0.0

### What is happening

- [ ] Issue 1: When a player updates Group Advantage in combat, other players get a couple of errors. Group Advantage is still successfully modified.

To reproduce: Need 2 players logged in, with PC tokens in combat with an enemy token. Attempt to manually modify Group Advantage during combat.

![image](https://user-images.githubusercontent.com/96636889/189528229-ea514162-83f4-4c2c-a8b2-b7fe67269486.png)

- [ ] Issue 2: Furthermore, when combat is ended, the Group Advantage values in the combat tracker correctly gets set to 0, but the tokens on the scene still retain any remaining advantage. When the player then tries to manually reset their advantage (via the character sheet, for example), they get a little message saying they aren't allowed to modify Group Advantage out of combat, but fortunately(?) does not actually stop them from removing the remaining advantage.

**Comment by Jagusti** [comment]
Thanks for these .... Can I just check both of these happen when you're not
using the Toolkit (ie, the module is not enabled)?

**Comment by Jagusti** [comment]
> Attempt to manually modify Group Advantage during combat.

By this in Issue 1, do you mean adjusting the Group Advantage fields in the Combat Tracker? If not, can you describe how it is manually adjusted please, eg, through their own character sheet, the Add Advantage macro, updating their Token Hud resource bar, etc ...

**Comment by Jagusti** [comment]
I believe Issue 2 is a WFRP4e issue. Certainly, this is a WFRP4e system notification message. 
![image](https://user-images.githubusercontent.com/521096/189616344-8fcaa925-2c17-4929-bb17-74af49b0f0b8.png)

And this is the console log which points to the WFRP4e system file where the error is raised. 
![image](https://user-images.githubusercontent.com/521096/189616872-27b31cf9-8b4e-41b1-82d0-a9e27181348e.png)

**Comment by Jagusti** [comment]
Looks like issue 1 may be related to switching between user and player accounts mid-combat testing. From a discussion with @TheFirst05 it's rare, and hasn't recurred in normal use, so the issue can be closed.
