### ISSUE TITLE
Incorrect behaviour of Session Turnover

### ISSUE THREAD

**Issue by RafPorrini** [Jagusti/fvtt-wfrp4e-gmtoolkit#186]
## Checklist

- [ ] I have disabled GM Toolkit and the issue doesn't happen.
- [ ] I have disabled all other modules (except GM Toolkit) and the issue still happens. 
- [ ] I go not get a [Spectator Notification](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki/spectators) related to actors affected by this issue.
- [x] I can be reached on Discord by my handle: rporrini#7932

### Versions
 - Foundry VTT:  
 - WFRP4e System: 
 - GM Toolkit:  
 - Macro (if applicable): 

## Steps to reproduce the issue
 "TypeError: pc.actor is undefined"

**Comment by Jagusti** [comment]
Resolved by assigning character to user.
