### ISSUE TITLE
Some toolkit macros not working as expected for player character actors/tokens

### ISSUE THREAD

**Issue by deadcatsmeow** [Jagusti/fvtt-wfrp4e-gmtoolkit#191]
## Checklist

- [x] I have disabled all other modules (except GM Toolkit) and the issue still happens. 
- [x] I do not get a [Spectator Notification](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki/spectators) related to actors affected by this issue.
- [x] I can be reached on Discord by my handle: Yoss#1583

### Versions
 - Foundry VTT: v10.286 
 - WFRP4e System: 6.1.4
 - GM Toolkit: 6.0.0
 - Macro (if applicable): Reset Fortune 0.9.5, Add XP 0.9.5, Make Secret Group Test 0.9.5, Session Turnover 0.9.5 

## Description
Hi, to preface: sorry if I have missed something really obvious, because it feels like these macros should just work, but I've looked and I have missed whatever that it is.

I have given ownership of actors to players, but macros that interact with Player Character actors/tokens are not behaving as expected.

This was happening in a world with many WFRP modules, but I have created a new clean world for testing.

### What should happen

**Reset Fortune**: Fortune is restored to Player Character actors  
**Add XP**: XP is added to targeted Player Character actor tokens  
**Make Secret Group Test**: Secret group test is rolled  
**Session Turnover**: Something more than just iterating the session number  

### What is happening

**Reset Fortune**: Error message "There are no player characters to restore Fortune for" and nothing happens  
**Add XP**: Error message "Please target one or more PC tokens first" and nothing happens  
**Make Secret Group Test**: Dialog box appears, but after clicking Perception button get Error message "Uncaught (in promise) TypeError: testOptions.targetGroup is not iterable at runGroupTest" and nothing happens   
**Session Turnover**: Update Session ID box appears, plus Error messages "There are no player characters to restore Fortune for" & "Please target one or more PC tokens first". Session ID is increased, but nothing otherwise happens.

## Steps to reproduce the issue
1. Create clean new world with WFRP4e System: 6.1.4
2. Add two players via User Management
3. Enable module GM Toolkit: 6.0.0
4. Import Macros using "Update GM Toolkit Content" and add relevant macros to macro bar
5. Create 2 new actors and change ownership of each (one for each player)
6. Add a couple of Fate points to both
6. Execute affected Macros, selecting/targeting tokens where required by macro

## Supporting Information 

Exported actor json (as txt files):
[JSONfvtt-Actor-new-actor.txt](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/9692222/JSONfvtt-Actor-new-actor.txt)
[JSONfvtt-Actor-new-actor-(2).txt](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/files/9692221/JSONfvtt-Actor-new-actor-.2.txt)

### Screen Capture

 
![foundry and console logs](https://user-images.githubusercontent.com/25388062/193449090-c6b08655-d4fa-4f9e-bd46-f3e3a8638f91.png)

### Modules and Settings
This is happening on a clean world with only GM Toolkit: 6.0.0 module enabled and macros and tables added via "Update GM Toolkit Content". Otherwise default settings for both WFRP4e System: 6.1.4 and GM Toolkit: 6.0.0

### Console Log

See Screen Capture

### Foundry Support Report

Foundry Virtual Tabletop: Version 10, 10.286
Game System: wfrp4e, 6.1.4
Active Modules: 1
Performance Mode: 1

OS: Unknown
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
GPU: ANGLE (Intel, Mesa Intel(R) Xe Graphics (TGL GT2), OpenGL 4.6)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2

Actors: 2 | Items: 0 | Journal: 0 | Rollable Tables: 1 |
Playlists: 0 | Compendium Packs: 3 | Chat Messages: 0

**Comment by Jagusti** [comment]
This is a super helpful bug report ... thanks @deadcatsmeow . 

What it all points to is that the characters are not _assigned_ to the players. This is different to ownership, but ownership is necessary before you can assign. 

1. Set Player as Owner to character
2. Expand player list and go to User Configuration
3. Assign Character to Player (only Owned characters appear here)

Try that out, and hopefully it works out. LMK the result.

![image](https://user-images.githubusercontent.com/521096/193475576-d0bf8813-c7f1-4f0d-9ed0-04f6034b7541.png)

**Comment by deadcatsmeow** [comment]
Yep, that was it. I figured I'd missed something really obvious, but am glad that was all it was. What is annoying is I had been into User Configuration, but only saw the one Player Character for each (as that is how I'm managing actor ownership unlike in your screenshot) and assumed those characters were assigned.

Thank you for the swift and helpful reply!

**Comment by Jagusti** [comment]
All good ... glad you managed to get it sorted. I was curious how you didn't get the Spectator notice though - I added that in explicitly to pre-empt this scenario, but it turns out I left it suppressed by default in module settings ... might have to change that :)
