### ISSUE TITLE
[Group Advantage] The Add Advantage macro does not increase Group Advantage past 10.

### ISSUE THREAD

**Issue by TheFirst05** [Jagusti/fvtt-wfrp4e-gmtoolkit#194]
Sometimes with Group Advantage we manage to accrue more than 10 advantage. The Add Advantage macro does not increase the value past 10. We need to manually change the number in the box of the Combat tracker to increase it. Is there a way to do this?

### Versions
 - All up to date as of this report.

## Console Log
Nothing in the console log

Edit: I've just worked out that its tied to max advantage right? Because Advantage automation does not increase past 10. This might have been for something for WFRP4e system instead of gmtoolkit. Sorry.

**Comment by Jagusti** [comment]
> This might have been for something for WFRP4e system instead of gmtoolkit.

TBF, as you can increase the Advantage above 10 editing the pool directly, so I'm happy the system is doing what it needs to. I'll add a check to ignore the max check if Group Advantage is being used.
