### ISSUE TITLE
Engaged status effect 

### ISSUE THREAD

**Issue by GregorHak** [Jagusti/fvtt-wfrp4e-gmtoolkit#206]
When pick Engaged status effect on character, character looses all advantages. Make sense for other status effect, but should not remove advantages when click Engaged.

![obraz](https://user-images.githubusercontent.com/99994770/205496347-5d037f89-794d-49de-b693-ed01db5df108.png)

**Comment by Jagusti** [comment]
Need to add "engaged" to https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/4778f6055f816293cbd8b03ed5a132ce4247a35d/modules/advantage.mjs#L452

If this list gets any bigger I might want to switch it out to a filter/includes check. 🤔
