### ISSUE TITLE
No Forge update

### ISSUE THREAD

**Issue by docphil30** [Jagusti/fvtt-wfrp4e-gmtoolkit#222]
GM Toolkit refuses to update to The Forge, it remains in version 6.0.1

**Comment by Jagusti** [comment]
I don't know how Forge updates modules @docphil30 but it's not something I can alter particularly. I should note that the latest version of GM Toolkit (6.0.3) requires at least WFRP4e system 6.4.0. So if that's not up-to-date, it won;t be recognised as compatible, 

I guess you can also import modules directly if that doesn't work: https://forums.forge-vtt.com/t/importing-worlds-modules-systems-w-video-tutorial/454

**Comment by Jagusti** [comment]
Looks like GM Toolkit 6.0.3 [is available on Forge](https://eu.forge-vtt.com/bazaar#sort=title&filter=all&search=%5B%22toolkit%22%5D&type=module). 

![image](https://user-images.githubusercontent.com/521096/235152935-8a36283f-5a58-445c-b359-d7ec018e71c6.png)

**Comment by docphil30** [comment]
Thx for you reply, The problem comes from the use of the latest version of WfRP (patch 6) which is not the one recommended by the Forge (patch 5 for the Forge)… I can import with the json link, but The forge reverse to 6.01 each update…

Envoyé à partir de Courrier pour Windows

De : Jag Goraya
Envoyé le :vendredi 28 avril 2023 12:27
À : Jagusti/fvtt-wfrp4e-gmtoolkit
Cc : docphil30; Mention
Objet :Re: [Jagusti/fvtt-wfrp4e-gmtoolkit] No Forge update (Issue #222)

I don't know how Forge updates modules @docphil30 but it's not something I can alter particularly. I should note that the latest version of GM Toolkit (6.0.3) requires at least WFRP4e system 6.4.0. So if that's not up-to-date, it won;t be recognised as compatible,
I guess you can also import modules directly if that doesn't work: https://forums.forge-vtt.com/t/importing-worlds-modules-systems-w-video-tutorial/454
