### ISSUE TITLE
Status Effect HUD background color makes it hard to use.

### ISSUE THREAD

**Issue by BoltsJ** [Jagusti/fvtt-wfrp4e-gmtoolkit#240]
## Checklist

- [x] I have disabled GM Toolkit and the issue doesn't happen.
- [x] I have disabled all other modules (except GM Toolkit) and the issue still happens. 
- [x] I go not get a [Spectator Notification](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki/spectators) related to actors affected by this issue.
- [x] I can be reached on Discord by my handle: boltsj

### Versions
 - Foundry VTT: 11.305
 - WFRP4e System:  6.6.1
 - GM Toolkit:   6.0.4
 - Macro (if applicable):  N/A

## Description
The change to the background color causes the contrast between most of the icons to be too low and makes visually locating them difficult

### What should happen
The 

## Steps to reproduce the issue
1. Open the token hud and select Assign Status Effects
2. The background is light grey

### Screen Capture
![Screenshot from 2023-07-30 12-23-27](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/assets/182554/be42c286-bbf4-4379-9fa1-9753fad7ee9f)

### Modules and Settings
Occurs even with "Token Hud Extensions" option disabled

### Foundry Support Report
Foundry Virtual Tabletop: Version 11 Stable, 11.305
Game System: wfrp4e, 6.6.1
Active Modules: 1
Performance Mode: 2

OS: Linux x86_64
Client: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
GPU: Radeon R9 200 Series
Max Texture Size: 16384

Scene: 17176 x 11400 | Grid Size: 76 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 5

Actors: 140 | Items: 0 | Journal Entries: 86 | Rollable Tables: 147 |
Playlists: 0 | Compendium Packs: 5 | Chat Messages: 0

**Comment by Jagusti** [comment]
@BoltsJ this will be in the next release. Preview shots in [PR](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/pull/284).
