### ISSUE TITLE
Can´t activate GMToolkit 6.0.4 with WFRP4e 7.0.1

### ISSUE THREAD

**Issue by DerHarm** [Jagusti/fvtt-wfrp4e-gmtoolkit#241]
## Checklist

- [ ] I have disabled GM Toolkit and the issue doesn't happen.
- [ ] I have disabled all other modules (except GM Toolkit) and the issue still happens. 
- [ ] I go not get a [Spectator Notification](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki/spectators) related to actors affected by this issue.
- [ ] I can be reached on Discord by my handle: ___

### Versions
 - Foundry VTT: V11 307 
 - WFRP4e System:  7.0.1
 - GM Toolkit:    6.0.4
 - Macro (if applicable): 

## Description
Module can´t be activated in module management. Error "This module requires a maximum Version of 6.x but your Version ist 7.0.1"

### What should happen
GMToolkit should be activated in the module management

### What is happening
Module can´t be activated in module management. Error "This module requires a maximum Version of 6.x but your Version ist 7.0.1", Therefore it can´t be activated in the module list

## Steps to reproduce the issue

1. Start Foundry V11 307, start WFRP4e 7.0.1
2. Select Game Settings and Manage Modules
3. Look for GMToolkit and the tick area is greyed out
4. "This module requires a maximum Version of 6.x but your Version ist 7.0.1"

**Comment by Jagusti** [comment]
The workaround for this is to change the max compatible system setting in `module.json` from "6.x" to "7.x".

https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/dev/module.json#L26

You'll need to restart Foundry for the change to be recognised.
