### ISSUE TITLE
Bypass Test Dialog option doesn't work when rolling Secret Group Tests after latest Foundry update

### ISSUE THREAD

**Issue by drplote-sep** [Jagusti/fvtt-wfrp4e-gmtoolkit#261]
### Versions
 - Foundry VTT: Version 11 Stable Build 315
 - WFRP4e System: 7.1.2
 - GM Toolkit:  6.0.5
 - Macro (if applicable): Make a Secret Group Test

### What should happen
When I roll a secret group test and have the "Bypass Test Dialog" checked, it should not pop up a test dialog for each actor needing to roll.

### What is happening
It is popping up a test dialog for each actor, one by one, meaning I need to click "Roll" for each before it finally gets to the summarized results.

## Steps to reproduce the issue
1. Make sure you've got a few actors eligible for a secret group test.
2. Make a secret group test for something like Perception with those actors selected.
3. Make sure the "Bypass Test Dialog" checkbox is checked.

**Comment by Forien** [comment]
It's a bug with WFRP4e itself

 - Source: https://github.com/moo-man/WFRP4e-FoundryVTT/issues/1993

**Comment by Forien** [comment]
Should be fixed in [wfrp4e 7.1.5](https://github.com/moo-man/WFRP4e-FoundryVTT/releases/tag/7.1.5) @drplote-sep
