### ISSUE TITLE
All Macros and Tables seem to have disappeared in latest update

### ISSUE THREAD

**Issue by mighty-chebo** [Jagusti/fvtt-wfrp4e-gmtoolkit#265]
## Checklist
- [ ] I have disabled all other modules (except GM Toolkit) and the issue still happens. 
- [X] I go not get a [Spectator Notification](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki/spectators) related to actors affected by this issue.
- [X] I can be reached on Discord by my handle: mighty_chebo

### Versions
 - Foundry VTT: V11 Stable - Patch 13 (Build 315) via The Forge 
 - WFRP4e System: 5.0.6
 - GM Toolkit:  7.0.0

### What should happen
GM Toolkit should contain usable Macros and Tables.

### What is happening
Since updating today, GM Toolkit seems to now contain no Macros or Tables. I have tried deactivating and reactivating the module, as well as running the prompted Macro and Table updates through the chat notification and settings menu. I tried to manually import the Macros and Tables from the GM Toolkit compendiums, but they appear to be empty.

## Steps to reproduce the issue
Try to use any GM Toolkit Macros or Tables.

### Screen Capture
![GM Toolkit](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/assets/172417715/c34d82e5-3230-4793-b1aa-e9816d572878)

### Modules and Settings
I have many other modules activated but don't have time to try de- and re-activating them as I have to run a game tonight.

**Comment by Jagusti** [comment]
It's possible the Forge version is cached and doesn't include the updated module package.  You can try downloading the zip file direct from the assets section of the release notes and unzipping in your Data/modules folder: https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/releases/tag/v7.0.0. I'm working on a fix to my release worklfow in the meantime.

**Comment by mighty-chebo** [comment]
> It's possible the Forge version is cached and doesn't include the updated module package. You can try downloading the zip file direct from the assets section of the release notes and unzipping in your Data/modules folder: https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/releases/tag/v7.0.0. I'm working on a fix to my release worklfow in the meantime.

Thank you. I tried adding the unzipped folder into the "modules" folder of my Assets Library, but it doesn't seem to have changed anything. I don't seem to be able to access any other module data folders beyond my Assets Library through The Forge, but I'm not especially savvy with it.

**Comment by Jagusti** [comment]
This is resolved in v7.0.3.  You may want to uninstall GM Toolkit completely before reloading and then downloading again.  There can be caching challenges with Forge.

**Comment by mighty-chebo** [comment]
> This is resolved in v7.0.3. You may want to uninstall GM Toolkit completely before reloading and then downloading again. There can be caching challenges with Forge.

Thank you very much. It all seems fine now.
