### ISSUE TITLE
Upadte to v12

### ISSUE THREAD

**Issue by ghost** [Jagusti/fvtt-wfrp4e-gmtoolkit#269]
Like in title. When we can expect that?

**Comment by Jagusti** [comment]
Not before WFRP4e system is certified for v1. Then I need to review changes that will need to be made. Once that's done, I'll likely set up a v12 compatibility ticket (like I did [for v11](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues/228)), and folks can see what the state of things are.
