### ISSUE TITLE
Token layout is broken in Safari

### ISSUE THREAD

**Issue by Heilemann** [Jagusti/fvtt-wfrp4e-gmtoolkit#35]
<img width="621" alt="Screen Shot 2020-08-11 at 10 43 57 PM" src="https://user-images.githubusercontent.com/203049/89969416-54ed6980-dc24-11ea-84fd-d5ede256c9ec.png">

This is on Big Sur, but I assume it would be the same in older versions of Safari. Works fine in Chrome on the same server, user etc.

**Comment by Jagusti** [comment]
Heya @Heilemann - I made some changes to the Token Hud layout a while back. Not been able to get access to a Big Sur device to test myself. Is this still an issue for you? I'm likely going to build on those changes make other layout updates, but good to know if this is continuing.

**Comment by bluetardis** [comment]
Did some testing today with Monterey 12.4 and Safari.   Very pleasantly surprised.  Not only is everything working (including .ogg, .webp, voice chat).

Also the token stuff works now too!  

![Screen Shot 2022-07-18 at 11 02 12 am](https://user-images.githubusercontent.com/5024761/179432391-2a927e82-e207-4126-954a-0fa184ce0813.png)

**Comment by bluetardis** [comment]
From my perspective it looks the same in Safari as in Thorium/Chromium.

**Comment by Jagusti** [comment]
That's great to hear - thanks for update. I'm going to go ahead and close this as resolved then. :)
