### ISSUE TITLE
Add advantage/Reduce advantage no more dynamic in 0.7.X

### ISSUE THREAD

**Issue by sladecraven** [Jagusti/fvtt-wfrp4e-gmtoolkit#39]
When using the advantages macros, they add/substract advantages point properly but the updated amount is not displayed in the HUD.
You need to deselect/select again the token to see the new value.

**Comment by sladecraven** [comment]
Marco should be : 
```
/* Increases Advantage for the selected token by 0 */

await actor.update({"data.status.advantage.value" : Number(actor.data.data.status.advantage.value)+1});
canvas.hud.token.render();
ui.notifications.notify(`Advantage increased by 1 to ${actor.data.name}`)
```

**Comment by Jagusti** [comment]
This is updated now for FVTT 0.7, including for the Clear Advantage macro and world setting.
