### ISSUE TITLE
Dark Whispers: Search for eligible actors (not players).

### ISSUE THREAD

**Issue by bluetardis** [Jagusti/fvtt-wfrp4e-gmtoolkit#58]
Can this be modified or can you suggest how to make this change please.

Currently this only works if:
Actor Created
Player Created
Actor Assigned to player
Player has logged in.
(Sometimes the GM then needs to refresh).

Use Case:
We use Hot Seat Observer module to allow local players to interact (4 at this point). And the issue is that it can only be assigned to 1 player at a time.

A modification to search the actors selected (vs players) would fix this.

Yes it means its possible to send out a dark whisper to a player who isn't in game but this is on the GM.

**Comment by Jagusti** [comment]
If I understand your use case correctly, you want to be able to send Dark Whispers to players who aren't logged in. 
This _should_ already be possible ... there is a GM Toolkit setting for selecting `Dark Whispers Targets` - which by default is all player characters, regardless of whether the player is logged in. 

![image](https://user-images.githubusercontent.com/521096/125605105-9a638ad0-cd7d-4b5d-a041-216485750a06.png)

You can also override that with a parameter in the macro script itself. The first uncommented line can be changed from 
`formDarkWhispers(); //  Set default user target filter in module settings. Override by adding parameter to 'all', 'absent' or 'present' party members. Clear parameter to revert to default.`
to 
`formDarkWhispers('all'); //  Set default user target filter in module settings. Override by adding parameter to 'all', 'absent' or 'present' party members. Clear parameter to revert to default.`
or 
`formDarkWhispers('absent'); //  Set default user target filter in module settings. Override by adding parameter to 'all', 'absent' or 'present' party members. Clear parameter to revert to default.`

Let me know if that does what you need it to.

**Comment by bluetardis** [comment]
Thanks for getting back to me. 

My settings are set as suggested and I did try the 'all' option earlier but it gave the same result.

I think the core problem is that it assumes a 1:1 player:character relationship.

The issue is that we have local players (between 2-4 people) who each have a character.  Using the "Hot Seat Observer Module" means they can share a kb/mouse as their turn comes up in combat or for any of their rolls/tests otherwise as the modules assigned player in Foundry has ownership of all of their characters so in this case 1:4.

In practical terms this means that the only character to receive a dark whisper is whomever was selected last by the module (eg who had the last turn in a combat round).   Hence my request to search across characters not players (ideally characters active on current scene).

**Comment by bluetardis** [comment]
link to that module is here
https://github.com/Zzarek/FoundryHotSeatObserver

**Comment by Jagusti** [comment]
Just to let you know, I've been exploring some ways to deal with this. 

For now though I want to focus on getting a v8 compatible Toolkit out there, so will likely migrate behaviour as-is to avoid delay.

**Comment by bluetardis** [comment]
I have a workaround:
1. Assign each "actor" to a real  "player" as owner.
2. Player from step1  logs in (at least once) and selects that actor.
3. Also give the player  player "HotSeat" owner.
4. Rinse and repeat for every other "player and their character/actor".  They must be unique eg each actor that might get dark whispers needs to be assigned to a player.

It will now work with just the GM and the Hot Seat player logged in.

**Comment by bluetardis** [comment]
Actually.... scratch that.  its half a solution.
The dark whispers get sent correctly to all players but...
the hot seat module only responds as the last player active in a combat round.  It shows that you have 4 characters receive a whisper but only one gets a chance to respond.

![Screen Shot 2021-07-28 at 10 21 42 am](https://user-images.githubusercontent.com/5024761/127244017-bd58e093-2b4a-4fef-8d3f-2a55af4583a9.png)

**Comment by bluetardis** [comment]
So... Leave it as a lower priority for now.  0.8 compatibility is more useful/important.

A fix would be (if this is possible).
If hotSeatModule = True 
   give option on the Dark Whisper Card to select the character you are responding as
else
   no need to show anything as its a 1:1 relationship
end

**Comment by bluetardis** [comment]
I am going to retest this in 0.9 and see how things go.  To be honest it hasnt come up since 0.8 due to covid meaning no group sessions...
