### ISSUE TITLE
Secret Group Tests: Add user interface to select and configure secret skill check parameters

### ISSUE THREAD

**Issue by Jagusti** [Jagusti/fvtt-wfrp4e-gmtoolkit#63]
Add user interface to more easily select target skills, rather than relying on macro editing.

- [x] select from list of available skills to test
- [x] offer 1-4 default options (single-click select button)
  - [x] add configurable user settings
- [x] option to default to base characteristic if skill is not available [v0.8.0](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/commit/c6e5f81c13379fa4844240d31708dc1c4041c41a)
- [x] present modifier options
- [x] present options for bypassing roll dialog
- [x] select from available actors

**Comment by Reppumaru** [comment]
Hey there. Can you add.

- [x] Interface to select Actors to make a secret Party test
