### ISSUE TITLE
Set Token Vision and Light Macro does not work in Foundry v9

### ISSUE THREAD

**Issue by TheFirst05** [Jagusti/fvtt-wfrp4e-gmtoolkit#68]
the macro "Set Token Vision and Light" no longer functions when using Foundry v9. Was probably to be expected since v9 changed how lighting is rendered.

Thanks.

**Comment by Jagusti** [comment]
Thanks ,- yes, it's probably not going to work with the v9 changes yet. Can you share any console log errors you got please?  Thanks

**Comment by TheFirst05** [comment]
I've hecked, and I just cant get an error to appear in the console log. After importing the macro from the compendium, I select a token, click the macro, select a lightsource, and click Apply Changes. Nothing happens. No error log. I doublechecked the token lighting settings, and nothing changes either. Sorry about that.

**Comment by Jagusti** [comment]
At the moment, updating token sight is [bugged in Foundry v9 core](https://gitlab.com/foundrynet/foundryvtt/-/issues/6389): a fix is expected in Stable Patch 1. 

Token light changes should process as expected, but vision updates do not process when multiple tokens are selected without moving or deselecting/reselecting first. 

From what I can see, sight changes are being processed when only a single token is selected.

**Comment by Jagusti** [comment]
The [core issue](https://gitlab.com/foundrynet/foundryvtt/-/issues/6389) has been pushed back to Version 9 Stable Patch 2, so will be more like tail end of of the month rather than early Jan.
