### ISSUE TITLE
End of Session 

### ISSUE THREAD

**Issue by danil0man** [Jagusti/fvtt-wfrp4e-gmtoolkit#85]
Hello I am getting an error when i try to use Add XP or Session TurnOver.
I am getting this errors and there is no xp added or the prompt to add xp
![image](https://user-images.githubusercontent.com/72052103/150229558-08169882-8cd3-416c-8bb1-e64399af87ac.png)

**Comment by danil0man** [comment]
I am using 
foundry version 9.242
Warhammer version 5.05
GM toolkit 0.92

**Comment by Jagusti** [comment]
Thanks @danil0man  ... 

- [ ] Can you confirm that you only have one version of the Add XP macro in your Macro Directory please? 
- [ ] Can you posted on here the macro code for Add XP that's in your Macro Directory (rather than the compendium).

**Comment by danil0man** [comment]
It seems Is working after I deactivate the Furnace and the dependency advanced macros.

**Comment by Jagusti** [comment]
Interesting ... ok, well - I'm pleased it works for you like that. Thanks for investigating. When I get a chance I will review for possible conflicts.
