### ISSUE TITLE
XP rewarding is unavailable 

### ISSUE THREAD

**Issue by geant14** [Jagusti/fvtt-wfrp4e-gmtoolkit#90]
It looks like my party is not able to get XP. Whenever I click on the macro to award them with xp I get a message like that. Am I the only one with the issue?
It worked before but since I swtich to version 9. It has stopped working. 
Thanks!
-J

<img width="303" alt="image" src="https://user-images.githubusercontent.com/71984083/162592283-5f6fdb23-574c-4c65-b6d6-9f49035c1c76.png">

**Comment by Jagusti** [comment]
This is resolved by #86, which is available currently on the dev branch. Disabling the Advanced Macros module also resolves this.

**Comment by geant14** [comment]
Great! It works 
thank you!

Envoyé à partir de Courrier pour Windows

De : Jag Goraya
Envoyé le :10 avril 2022 07:22
À : Jagusti/fvtt-wfrp4e-gmtoolkit
Cc : geant14; Author
Objet :Re: [Jagusti/fvtt-wfrp4e-gmtoolkit] XP rewarding is unavailable (Issue #90)

This is resolved but #90, which is available currently on the dev branch. Disabling Advanced Macros module also resolves this.
